### ISSUE TITLE
Proper es6 support (command line + Docker) 

### ISSUE THREAD

**Issue by pigne** [pigne/sensors-to-db#4]
Although `babel-node` is not meant to be used in production, we still need to compile the script (just in case we want to use es6, imports, exports, ...)  before running it. 

So something like :

```bash
./node_modules/.bin/babel  ./src --experimental -d ./dist
```
and then run the result script in the `dist` folder

```bash
node dist/sensors-to-db.js
```

**Comment by pigne** [comment]
cc: @remnil  @bachrc

**Comment by bachrc** [comment]
When I launch the following command (which seems right to me), I have a weird exception.
```bash
babel . -x ".js",".jsx" -d dist/

config.js -> dist\config.js
model\Measure.js -> dist\model\Measure.js
model\Sensor.js -> dist\model\Sensor.js
mongodb.js -> dist\mongodb.js
ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "F:\\Dropbox\\Notes\\IDOD\\sensors-to-db\\node_modules\\babel-preset-env\\package.json" at 0, attempted to resolve relative to "F:\\Dropbox\\Notes\\IDOD\\sensors-to-db\\node_modules\\babel-preset-env"
    at F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\options\option-manager.js:233:36)
    at OptionManager.init (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\options\option-manager.js:367:12)

    at File.initOptions (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (F:\Dropbox\Notes\IDOD\sensors-to-db\node_modules\babel-cli\lib\babel\util.js:59:12)
```

It's not pretty, and don't know where this is coming from. I'll search further more when I finish the API.

**Comment by bachrc** [comment]
Nevermind, I wouldn't have slept if i didn't find the bug. @remnil gave me a hand, and the image automatically compiles the scripts. I reorganized the structure, and even added a working docker-compose example. You can try it. https://github.com/pigne/sensors-to-db/pull/5

**Comment by pigne** [comment]
Good job @bachrc and @remnil! Thanks!
